# This is a basic workflow that is manually triggered

name: Test Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: 
  pull_request:
    branches: [master]
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
        TEST_SECRET: ${{ secrets.TEST_SECRET }}
        SECRET_TOO: "testing this out"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      shell: pwsh
      run: |
        Write-Host "$env:SECRET_TOO"
        Write-Host "test_environment=dev" >> $GITHUB_ENV
    - name: Use value
      shell: pwsh
      run: |
        Write-Host "${{ env.test_environment }}"
